# Generated by Django 3.2.8 on 2021-11-01 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_note_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['updated']},
        ),
    ]
